apiVersion: training.eduk8s.io/v1alpha1
kind: SystemProfile
metadata:
  name: local-development-profile
spec:
  portal:
    #image: registry.eduk8s.svc.cluster.local:5001/eduk8s-portal:latest
    credentials:
      admin:
        username: educates
        password: my-pasword
      robot:
        username: robot@educates
        password: my-pasword
    clients:
      robot:
        id: robot
        secret: robot
  storage:
    group: 1
  dockerd:
    mtu: 1350
  #workshop:
  #  images:
  #    base-environment:*: registry.eduk8s.svc.cluster.local:5001/base-environment:latest
  #    jdk8-environment:*: registry.eduk8s.svc.cluster.local:5001/jdk8-environment:latest
  #    jdk11-environment:*: registry.eduk8s.svc.cluster.local:5001/jdk11-environment:latest
  #    conda-environment:*: registry.eduk8s.svc.cluster.local:5001/conda-environment:latest
